export const clinicConfig = {
  veterinary: {
    patientLabel: "Mascota",
    patientsLabel: "Mascotas",
    ownerLabel: "Dueño",
    ownersLabel: "Dueños",
    patientType: "animal",
    showSpecies: true,
    showBreed: true,
    showAnimalGender: true,
    requiresOwner: true,
    showOwners: true,
    adultCheck: false,
    showBloodType: false,
    showAllergies: true,
    showChronicConditions: false,
    showMicrochip: true,
    showReproductiveStatus: true,
  },
  pediatric: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    ownerLabel: "Tutor / Responsable",
    ownersLabel: "Tutores",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: true,
    showOwners: true,
    adultCheck: false,
    showBloodType: true,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
  },
  general: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: true,
    showBloodType: true,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
  },
  dental: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: false,
    adultCheck: true,
    showBloodType: true,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
  },
  psychology: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    ownerLabel: "Tutor / Responsable",
    ownersLabel: "Tutores",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: false,
    adultCheck: true,
    showBloodType: false,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
  },

  // ── Servicios de bienestar y fitness ────────────────────────────────────────

  physiotherapy: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: false,
    adultCheck: true,
    showBloodType: false,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
  },

  nutrition: {
    patientLabel: "Cliente",
    patientsLabel: "Clientes",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: false,
    adultCheck: true,
    showBloodType: false,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
  },

  // ── Servicios generales con citas ────────────────────────────────────────────

  beauty: {
    patientLabel: "Cliente",
    patientsLabel: "Clientes",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: false,
    adultCheck: false,
    showBloodType: false,
    showAllergies: false,
    showChronicConditions: false,
    showMicrochip: false,
    showReproductiveStatus: false,
  },

  coaching: {
    patientLabel: "Coachee",
    patientsLabel: "Coachees",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: false,
    adultCheck: false,
    showBloodType: false,
    showAllergies: false,
    showChronicConditions: false,
    showMicrochip: false,
    showReproductiveStatus: false,
  },

  legal: {
    patientLabel: "Cliente",
    patientsLabel: "Clientes",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: false,
    adultCheck: false,
    showBloodType: false,
    showAllergies: false,
    showChronicConditions: false,
    showMicrochip: false,
    showReproductiveStatus: false,
  },

  fitness: {
    patientLabel: "Atleta",
    patientsLabel: "Atletas",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: false,
    adultCheck: false,
    showBloodType: false,
    showAllergies: false,
    showChronicConditions: false,
    showMicrochip: false,
    showReproductiveStatus: false,
  },
};

export const getConfig = (clinicType) => {
  return clinicConfig[clinicType] || clinicConfig.general;
};
