export const clinicConfig = {
  veterinary: {
    patientLabel: "Mascota",
    patientsLabel: "Mascotas",
    staffLabel: "Veterinarios",
    staffSingularLabel: "Veterinario",
    ownerLabel: "Dueño",
    ownersLabel: "Dueños",
    patientType: "animal",
    showSpecies: true,
    showBreed: true,
    showAnimalGender: true,
    requiresOwner: true,
    showOwners: true,
    adultCheck: false,
    showBloodType: false,
    showAllergies: true,
    showChronicConditions: false,
    showMicrochip: true,
    showReproductiveStatus: true,
    // Registro clínico
    businessLabel: "Clínica Veterinaria",
    recordLabel: "Consulta",
    recordType: "veterinary",
    showVitals: ["weight", "temperature", "heart_rate", "respiratory_rate"],
    showSOAP: true,
    showMedications: true,
  },
  pediatric: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    staffLabel: "Doctores",
    staffSingularLabel: "Doctor",
    ownerLabel: "Tutor / Responsable",
    ownersLabel: "Tutores",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: true,
    showOwners: true,
    adultCheck: false,
    showBloodType: true,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Clínica Pediátrica",
    recordLabel: "Consulta",
    recordType: "medical",
    showVitals: ["weight", "height", "temperature", "oxygen_saturation", "heart_rate", "respiratory_rate", "blood_pressure_systolic", "blood_pressure_diastolic"],
    showSOAP: true,
    showMedications: true,
  },
  general: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    staffLabel: "Doctores",
    staffSingularLabel: "Doctor",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: true,
    showBloodType: true,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Clínica Médica",
    recordLabel: "Consulta",
    recordType: "medical",
    showVitals: ["weight", "height", "temperature", "oxygen_saturation", "heart_rate", "respiratory_rate", "blood_pressure_systolic", "blood_pressure_diastolic"],
    showSOAP: true,
    showMedications: true,
  },
  dental: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    staffLabel: "Odontólogos",
    staffSingularLabel: "Odontólogo",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: true,
    showBloodType: true,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Clínica Dental",
    recordLabel: "Consulta",
    recordType: "dental",
    showVitals: [],
    showSOAP: false,
    showMedications: true,
  },
  psychology: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    staffLabel: "Psicólogos",
    staffSingularLabel: "Psicólogo",
    ownerLabel: "Tutor / Responsable",
    ownersLabel: "Tutores",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: true,
    showBloodType: false,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Consultorio Psicológico",
    recordLabel: "Sesión",
    recordType: "psychology",
    showVitals: [],
    showSOAP: false,
    showMedications: false,
  },

  // ── Servicios de bienestar y fitness ────────────────────────────────────────

  physiotherapy: {
    patientLabel: "Paciente",
    patientsLabel: "Pacientes",
    staffLabel: "Fisioterapeutas",
    staffSingularLabel: "Fisioterapeuta",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: true,
    showBloodType: false,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Centro de Fisioterapia",
    recordLabel: "Sesión",
    recordType: "physio",
    showVitals: ["weight"],
    showSOAP: false,
    showMedications: false,
  },

  nutrition: {
    patientLabel: "Cliente",
    patientsLabel: "Clientes",
    staffLabel: "Nutricionistas",
    staffSingularLabel: "Nutricionista",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: true,
    showBloodType: false,
    showAllergies: true,
    showChronicConditions: true,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Consultorio Nutricional",
    recordLabel: "Consulta",
    recordType: "nutrition",
    showVitals: ["weight", "height"],
    showSOAP: false,
    showMedications: false,
  },

  // ── Servicios generales con citas ────────────────────────────────────────────

  beauty: {
    patientLabel: "Cliente",
    patientsLabel: "Clientes",
    staffLabel: "Profesionales",
    staffSingularLabel: "Profesional",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: false,
    showBloodType: false,
    showAllergies: false,
    showChronicConditions: false,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Centro de Belleza",
    recordLabel: "Atención",
    recordType: "session",
    showVitals: [],
    showSOAP: false,
    showMedications: false,
  },

  coaching: {
    patientLabel: "Coachee",
    patientsLabel: "Coachees",
    staffLabel: "Coaches",
    staffSingularLabel: "Coach",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: false,
    showBloodType: false,
    showAllergies: false,
    showChronicConditions: false,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Centro de Coaching",
    recordLabel: "Sesión",
    recordType: "session",
    showVitals: [],
    showSOAP: false,
    showMedications: false,
  },

  legal: {
    patientLabel: "Cliente",
    patientsLabel: "Clientes",
    staffLabel: "Abogados",
    staffSingularLabel: "Abogado",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: false,
    showBloodType: false,
    showAllergies: false,
    showChronicConditions: false,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Despacho Legal",
    recordLabel: "Caso",
    recordType: "session",
    showVitals: [],
    showSOAP: false,
    showMedications: false,
  },

  fitness: {
    patientLabel: "Atleta",
    patientsLabel: "Atletas",
    staffLabel: "Entrenadores",
    staffSingularLabel: "Entrenador",
    ownerLabel: "Responsable",
    ownersLabel: "Responsables",
    patientType: "human",
    showSpecies: false,
    showBreed: false,
    showAnimalGender: false,
    requiresOwner: false,
    showOwners: true,
    adultCheck: false,
    showBloodType: false,
    showAllergies: false,
    showChronicConditions: false,
    showMicrochip: false,
    showReproductiveStatus: false,
    // Registro clínico
    businessLabel: "Centro Deportivo",
    recordLabel: "Sesión",
    recordType: "session",
    showVitals: [],
    showSOAP: false,
    showMedications: false,
  },
};

export const getConfig = (clinicType) => {
  return clinicConfig[clinicType] || clinicConfig.general;
};
